[package]
name = "mlnx"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "nix"
path = "main.rs"

[dependencies]
anyhow = "1.0.70"
melior = { package = "theos_melior", path  = "../melior" } 
rnix = "0.11.0"
